In [2]:
%load_ext kedro.ipython

[03/17/26 17:35:14] INFO     Using                                                                  ]8;id=791693;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=313044;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\framework\project\__init__.py#269\269]8;;\
                             'C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\
                             Lib\site-packages\kedro\framework\project\rich_logging.yml' as logging
                             configuration.

                    INFO     Registered line magic '%reload_kedro'                                   ]8;id=806191;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=534252;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\ipython\__init__.py#64\64]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=944790;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=726877;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\ipython\__init__.py#66\66]8;;\

                    INFO     Resolved project path as:                                              ]8;id=249734;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=472019;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\ipython\__init__.py#181\181]8;;\
                             C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights.
                             To set a different path, run '%reload_kedro <project_root>'

[03/17/26 17:35:30] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=252252;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=315046;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro_telemetry\plugin.py#242\242]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

[03/17/26 17:35:31] INFO     Kedro project spaceflights                                             ]8;id=898484;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=279329;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\ipython\__init__.py#147\147]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=761409;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=893082;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\ipython\__init__.py#148\148]8;;\
                             'pipelines'

[03/17/26 17:35:32] INFO     Registered line magic 'run_viz'                                        ]8;id=578522;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=795298;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\ipython\__init__.py#154\154]8;;\

In [4]:
companies = catalog.load('companies')
reviews = catalog.load('reviews')
shuttles = catalog.load('shuttles')

[03/17/26 17:38:17] INFO     Loading data from companies (CSVDataset)...                       ]8;id=629317;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=756427;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from reviews (CSVDataset)...                         ]8;id=600175;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=251510;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from shuttles (ExcelDataset)...                      ]8;id=696627;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=895832;file://C:\Users\alarc\OneDrive\Escritorio\Proyecto_Kedro\spaceflights\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

In [6]:
companies.describe()

,id,engines,passenger_capacity,crew,company_id
count,15531.000000,15525.000000,15531.000000,15485.000000,15531.000000
mean,38550.051574,1.401095,3.177709,1.746271,25117.928659
std,22227.045210,0.896879,1.950474,1.230954,14450.930370
min,3.000000,0.000000,1.000000,0.000000,1.000000
25%,19327.500000,1.000000,2.000000,1.000000,12783.500000
50%,38665.000000,1.000000,2.000000,1.000000,24844.000000
75%,57617.000000,2.000000,4.000000,2.000000,37646.000000
max,77096.000000,8.000000,20.000000,16.000000,50098.000000

In [11]:
companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10019 entries, 0 to 10018
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10019 non-null  int64
 1   company_rating     4941 non-null   object
 2   company_location   6873 non-null   object
 3   total_fleet_count  10017 non-null  float64
 4   iata_approved      10017 non-null  object
dtypes: float64(1), int64(1), object(3)
memory usage: 391.5+ KB

In [12]:
companies.head(4)

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,100%,Isle of Man,1.0,f
1,46728,100%,NaN,1.0,f
2,34618,38%,Isle of Man,1.0,f
3,28619,100%,Bosnia and Herzegovina,1.0,f

In [7]:
reviews.describe()

,shuttle_id,review_scores_rating,review_scores_comfort,review_scores_amenities,review_scores_trip,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month
count,15531.000000,11174.000000,11164.000000,11167.000000,11153.000000,11165.000000,11149.00000,11148.000000,15531.000000,11505.000000
mean,38550.051574,92.661983,9.516482,9.272678,9.634986,9.671294,9.48399,9.274130,15.214410,1.277311
std,22227.045210,10.002910,0.957390,1.144601,0.873809,0.864195,0.83391,1.009876,32.377659,1.477095
min,3.000000,20.000000,2.000000,2.000000,2.000000,2.000000,2.00000,2.000000,0.000000,0.010000
25%,19327.500000,90.000000,9.000000,9.000000,10.000000,10.000000,9.00000,9.000000,0.000000,0.280000
50%,38665.000000,96.000000,10.000000,10.000000,10.000000,10.000000,10.00000,9.000000,4.000000,0.790000
75%,57617.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.00000,10.000000,15.000000,1.730000
max,77096.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.00000,10.000000,501.000000,16.560000

In [13]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15531 entries, 0 to 15530
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   shuttle_id               15531 non-null  int64
 1   review_scores_rating     11174 non-null  float64
 2   review_scores_comfort    11164 non-null  float64
 3   review_scores_amenities  11167 non-null  float64
 4   review_scores_trip       11153 non-null  float64
 5   review_scores_crew       11165 non-null  float64
 6   review_scores_location   11149 non-null  float64
 7   review_scores_price      11148 non-null  float64
 8   number_of_reviews        15531 non-null  int64
 9   reviews_per_month        11505 non-null  float64
dtypes: float64(8), int64(2)
memory usage: 1.2 MB

In [14]:
reviews.head(4)

,shuttle_id,review_scores_rating,review_scores_comfort,review_scores_amenities,review_scores_trip,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month
0,45163,91.0,10.0,9.0,9.0,9.0,9.0,9.0,26,0.77
1,49438,96.0,10.0,10.0,10.0,10.0,10.0,9.0,61,0.62
2,10750,97.0,10.0,10.0,10.0,10.0,10.0,10.0,467,4.66
3,4146,95.0,10.0,10.0,10.0,10.0,9.0,9.0,318,3.22

In [8]:
shuttles.describe()

,id,engines,passenger_capacity,crew,company_id
count,15531.000000,15525.000000,15531.000000,15485.000000,15531.000000
mean,38550.051574,1.401095,3.177709,1.746271,25117.928659
std,22227.045210,0.896879,1.950474,1.230954,14450.930370
min,3.000000,0.000000,1.000000,0.000000,1.000000
25%,19327.500000,1.000000,2.000000,1.000000,12783.500000
50%,38665.000000,1.000000,2.000000,1.000000,24844.000000
75%,57617.000000,2.000000,4.000000,2.000000,37646.000000
max,77096.000000,8.000000,20.000000,16.000000,50098.000000

In [9]:
shuttles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15531 entries, 0 to 15530
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       15531 non-null  int64
 1   shuttle_location         15531 non-null  object
 2   shuttle_type             15531 non-null  object
 3   engine_type              15531 non-null  object
 4   engine_vendor            15531 non-null  object
 5   engines                  15525 non-null  float64
 6   passenger_capacity       15531 non-null  int64
 7   cancellation_policy      15531 non-null  object
 8   crew                     15485 non-null  float64
 9   d_check_complete         15531 non-null  object
 10  moon_clearance_complete  15531 non-null  object
 11  price                    15531 non-null  object
 12  company_id               15531 non-null  int64
dtypes: float64(2), int64(3), object(8)
memory usage: 1.5+ MB

In [10]:
shuttles.head(4)

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,price,company_id
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,f,f,"$1,715.0",32413
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,f,f,"$3,405.0",14122
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,t,f,"$1,806.0",47761
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,f,f,"$1,676.0",26648